server:
  port: 10000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      routes:
        - id: product_route
          uri: lb://lx-product
          predicates:
           - Path=/sell/buyer/**
          filters:
           - StripPrefix=2
          order: 0