server:
  port: 9099
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/1703a?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  resources:
    static-locations: file:${file.path}
    servlet:
      multipart:
        max-request-size: 10240000
        max-file-size: 10240000
  file:
    path: F:/pic
    domain: http://127.0.0.1:9099/
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true  #格式化sql
    hibernate:
      ddl-auto: update